config/routes.rb
Rails.application.routes.draw do

  get '/auth/twitter', as: :sign_in_with_twitter
  get '/auth/:provider/callback' => 'callbacks#index'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]


  # When we receive a 'GET' request with URL '/about', then Rails will invoke
  # the 'about_controller' with 'index' action (action is just a method that is
  # defined within a controller)
  get('/about', { to: 'about#index' })
  # or without the brackets...
  # get '/about', to: 'about#index'

  # you can also write it as:
  # get('/about' => 'about#index')

  # if you don't pass an 'as:' option, then Rails will attempt to generate a URL
  # / PATH helper for you. If you pass the 'as:' option, then Rails will use that
  # as the URL/PATH helper. The auto-generated path helper will be
  # 'contact_us_path', while after we added the 'as:' option, it will just be
  # 'contact_path'
  get('/contact_us', { to: 'contact#new', as: 'contact' })
  # get'/contact_us' => 'contact#new', as: 'contact'

  post('/contact', { to: 'contact#create', as: 'contact_submit' })

  # resources :contacts, only: [:new, :create]

  # 'default: { format: :json }' will prevent looking for a default of html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # /api/v1/questions.json # => INDEX
      # /api/v1/questions/1.json # => SHOW
      resources :questions, only: [:index, :show, :create]
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
    # Nesting resources :answers, only: [:create, :destroy] in resources :questions
    # will create routes for create and destroy (or all routes if not specified)
    # When using their helper methods to generate ths path to the routes (e.g.
    # question_answers_path) make sure to include a question_id as argument or
    # a question model.
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :users, only: [:new, :create] do
    resources :likes, only: [:index]
  end

  resources :sessions, only: [:new, :create] do
    # when you define a route with 'on: :collection' option, it skips having an
    # ':id' or ':session_id' as part of the generated url.
    delete :destroy, on: :collection
  end

  # get('/questions/new', { to: 'questions#new', as: 'new_question' })
  # post('/questions', { to: 'questions#create', as: 'questions' })
  #
  # # The order of the url matteres because Rails gives higher priority for routes
  # # that appear first. If the below were listed before '/questions/new',
  # # '/questions/new' would try to load 'questions#show'.
  # get('/questions/:id', { to: 'questions#show', as: 'question' })
  #
  # # Note that we don't need to put 'as:' option in here because we used the same
  # # URL for the create action. Verb doesn't matter. 'questions_path' was already
  # # defined for 'post('/questions')'. Rails will throw an error if you try to
  # # reuse a predefined path helper. Remember that is 'as:' option defines a
  # # path/url helper, which only generates a url and isn't concerned about the
  # # verb.
  # get('/questions', { to: 'questions#index' })
  #
  # get('/questions/:id/edit', { to: 'questions#edit', as: 'edit_question' })
  #
  # patch('/questions/:id', { to: 'questions#update' })
  #
  # delete('/questions/:id', { to: 'questions#destroy' })

  # the home page is a little different...
  # this will make the home page of the application go to WelcomeController with
  # index action.
  root 'welcome#index'

end

app/models/question.rb
# This is our Question model. It inherits from 'ApplicationRecord', which inherits
# from 'ActiveRecord::Base', which is a class that comes from Rails.
# All the functionalities we're going to be using in our Question model come from
# 'ActiveRecord::Base', which leverages Ruby's meta programming features.
class Question < ApplicationRecord
  attr_accessor :tweet_this

  # dependent: :destroy will delete all the associated answers before deleting
  # the question when you call 'question.destroy'
  # dependent: :nullify will update the 'question_id' field to 'null' in all the
  # associated answers before deleting the question when you call 'question.destroy'
  # remember to always have a dependent option
  has_many :answers, lambda { order(created_at: :desc) }, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  # 'through: :likes' is referring to the 'has_many :likes' relationship above,
  # not the 'Like' table.

  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # has_many :answers adds the following instance methods to this model,
  # Questions:
  # answers
  # answers<<(object, ...)
  # answers.delete(object, ...)
  # answers.destroy(object, ...)
  # answers=(objects)
  # answers_singular_ids
  # answers_singular_ids=(ids)
  # answers.clear
  # answers.empty?
  # answers.size
  # answers.find(...)
  # answers.where(...)
  # answers.exists?(...)
  # answers.build(attributes = {}, ...)
  # answers.create(attributes = {})
  # answers.create!(attributes = {})
  # http://guides.rubyonrails.org/association_basics.html#has-many-association-reference

  # as of Rails 5, belongs_to :subject will enforce a validation that the
  # association must be present by default (subject required). To make it optional
  # give 'belongs_to' a second argument, 'optional: true'
  belongs_to :subject, optional: true

  belongs_to :user, optional: true

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  mount_uploader :image, ImageUploader

  validates(:title, { presence: { message: 'must be present!' },
  # can use your own message instead of just 'true'
                      uniqueness: true })
  validates(:body, { presence: true, length: { minimum: 5 } })
  validates(:view_count, { presence: true,
                           numericality: { greater_than_or_equal_to: 0 } })

  # this is used fo custom-validation method. We expect to have a method called
  # 'no_monkey' defined, ideally in the private section of the class.
  validate :no_monkey

  after_initialize :set_defaults
  before_validation :titleize_title

  # class method... (do not have to call .new to use)
  def self.recent_five
    order(created_at: :desc).limit(5)
  end
  # can also write the above as...
  # scope :recent_five, lambda { order(created_at: :desc).limit(5) }

  def self.recent(number)
    order(created_at: :desc).limit(number)
  end

  def liked_by?(user)
    likes.exists?(user: user)
  end

  def like_for(user)
    likes.find_by(user: user)
  end

  def votes_count
    # TO DO: Attempt the below in a single query
    votes.where(is_up: true).count - votes.where(is_up: false).count
  end

  # Rails uses 'to_param' method in ActiveRecord to know what to use for the
  # URL. By default, 'to_param' method will return the 'id'.
  # def to_param
  #   "#{id.to_s}-#{title}".parameterize
  # end

  private

  def titleize_title
    self.title = title.titleize if title.present?
  end

  def set_defaults
    self.view_count ||= 0 # set equal to zero if no number provided
  end

  def no_monkey
    if title.present? && title.downcase.include?('monkey')
      # This will make the record invalid. Even if there is one error on the
      # record by using 'errors.add', then the record won't save because it
      # won't be valid.
      errors.add(:title, 'cannot include monkey!')
    end
  end

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::BaseController
  # http://localhost:3000/api/v1/questions
  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @question = Question.find params[:id]

    # if the format is JSON and we're using jbuilder as our templating system,
    # what file will be rendered?
    # /views/api/v1/questions/show.json.jbuilder

    # Using 'render' with 'json: @question' will use the Serializer for the
    # Question model.
    # render json: @question

    # Using 'render :show' or no render at all will use the corresponding view
    # for the specified format (e.g. jbuilder for json).
    render :show
  end

  def create
    question_params = params.require(:question).permit(:title, :body)
    # {question: {title: 'asdfasdf', body: 'asdfasdfasdf'}}
    question = Question.new question_params
    question.user = @user

    if question.save
      head :ok
    else
      render json: {error: question.errors.full_messages.join(', ') }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  # The 'before_action' method registers another method. In this case it's the
  # 'find_question' method, which will be executed just before the actions you
  # specify in the 'only' array. Keep in mind that the method that gets executed
  # as a 'before_action' happens within the save request/response cycle, so if
  # you define an instance variable, you can use it within the action/views.
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  def new
    # we create a new 'Question' object because it will help us in
    # generating the form in 'view/new.html.erb'. We have to make it an
    # instance variable so we can access it in the view file.
    @question = Question.new
  end

  # params look like:
  # {
  #   "utf8": "✓",
  #   "authenticity_token": "sVAh0/fbnVgaOqSqzbg9Q9N3J7XJzrf4pgJMU3A1w1ykin3ERqxnAszph6fHqGxb7KmEdnsZ9O/k5SDPKCebZQ==",
  #   "question": {
  #     "title": "abc",
  #     "body": "xyz"
  #   },
  #   "commit": "Create Question",
  #   "controller": "questions",
  #   "action": "create"
  # }

  def create
    # the line below is what's called "Strong Parameters" feature that was added
    # to Rails starting with version 4 to help developers be more explicit about
    # the parameters that they want to allow the user to submit.
    # question_params = params.require(:question).permit([:title, :body])
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      if @question.tweet_this
        client.update @question.title
      end

      RemindQuestionOwnerJob.set(wait: 5.days).perform_later(@question.id)
      # Rails gives us access to 'flash' object, which looks like a Hash. flash
      # utilizes cookies to store a bit of information that we can access in the
      # next request. Flash will automatically be deleted when it is displayed.
      flash[:notice] = 'Question created!'
      redirect_to question_path(@question)
      # render plain: 'Question created successfully'
    else
      # by default, Rails will try to render 'views/questions/create.html.erb'

      # If you want to show a flash message when you're doing 'render' instead
      # of 'redirect', meaning that you want to show the flash message within the
      # same request/response cycle, then you will need to use flash.now
      flash.now[:alert] = 'Please fix errors below'
      render :new
      # the above is the same as: render 'questions/new'
      # render plain: "Errors: #{question.errors.full_messages.join(', ')}"
    end

    # # can log errors to the console
    # Rails.logger.info '>>>>>>>>>>>>'
    # Rails.logger.info question.errors.full_messages
    # Rails.logger.info '>>>>>>>>>>>>'
    # render json: params
  end

  # {
  #   "controller": "questions",
  #   "action": "show",
  #   "id": "245"
  # }
  def show
    @answer = Answer.new
    # by default, renders 'questions/show' view

    # 'respond_to' method allows us to render different outcomes depending on
    # the format of the request. Remember that the default format for any
    # request in Rails appications is HTML.
    respond_to do |format|
      # the below means that if the format of the request is HTML, then we will
      # render the 'show' template (questions/show.html.erb)
      format.html { render :show }

      # the below will render 'json' if the format of the request is JSON.
      # ActiveRecord has a built-in feature to generate JSON from any object of
      # ActiveRecord.
      format.json { render json: @question }
    end
  end

  def index
    @questions = Question.last(20)
  end

  def edit
    # can? is a helper method that came from CanCanCan, which helps us enforce
    # permission rules in the controllers and views.
    redirect_to root_path, alert: 'Access denied' unless can? :edit, @question
  end

  def update
    if !(can? :edit, @question)
      # if the user does not have permission to edit/update the question, redirect
      redirect_to root_path, alert: 'Access denied' unless can? :edit, @question
    elsif @question.update(question_params.merge({ slug: nil }))
      redirect_to question_path(@question), notice: 'Question Updated'
    else
      render :edit
    end
  end

  def destroy
    if can? :destroy, @question
      @question.destroy
      redirect_to questions_path, notice: 'Question Deleted'
    else
      redirect_to root_path, alert: 'Access denied'
    end
  end

  private

  def find_question
    @question = Question.find params[:id]
  end

  def question_params
    params.require(:question).permit([:title, :body, { tag_ids: [] }, :image, :tweet_this ])
  end

  def client
    ::Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TWITTER_API_KEY']
      config.consumer_secret     = ENV['TWITTER_SECRET_KEY']
      config.access_token        = current_user.oauth_token
      config.access_token_secret = current_user.oauth_secret
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%# Partial file names usually start with an underscore, by convention. %>

<%# If you pass a persisted ActiveRecord object to the 'form_for' (in the DB),
then 'form_for' will submit a 'PATCH' request (instead of POST) using a
hidden_field technique and the url for hte form will be in this case the'update'
action url, which is in our case quesetion_path(@question) %>

<%# form_for is a built-in Rails helper that enables us to generate a form for
an ActiveRecord model to submit to the associated controller. If you pass in
a non-persisted ActiveRecord object (not in the DB yet) then 'form_for' will
automatically assume that this form will submit to the 'create' action in
the associated controller (in our case, questions#create), which has a path
helper of 'questions_path'. So we must have 'questions_path' defined.

If '@question' has values set to it already, then the form will be prepopulated
with those values. %>

<%= simple_form_for @question do |f| %>
  <%= f.input :title %>
  <%= f.input :body, required: false %>
  <%= f.association :tags, input_html: { class: 'chosen-select input-new-line',
                                         style: 'width: 400px' } %>
  <%= f.input :image %>

  <% if !@question.persisted? && current_user.signed_in_with_twitter? %>
    <div>
      <%= f.check_box :tweet_this %>
      <%= f.label :tweet_this %>
    </div>
  <% end %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |question| %>
  <h3><%= link_to question.title, question_path(question) %></h3>
  <hr>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%# render helps you insert (or render) a partial, so Rails expects in here
that you've defined a partial within the same folder as this file (new.html.erb)
called '_form.html.erb'. So the file path should be:
'/app/views/question/_form.html.erb'
Note that partials will have access to instance variables, so there is no need
to pass them explicitly. If you want to pass a local variable, then you will
need to do so explicitly, as in: render 'form', my_var: 'abc'
Also, if the partial is in another folder, such as contact, then you will have
to put the full path for the partial, as in: render '/contact/form' %>
<%= render 'form' %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p>Created On: <%= standard_date_format(@question.created_at) %></p>

<!-- <p><strong>Subject: </strong><%= @question.subject.name if @question.subject %></p> -->
<p><strong>Subject: </strong><%= @question.subject&.name %></p>
<%# '...subject&.name' will return nil if the value of subject is nil, rather
than crashing your server %>

<p>Tags: <%= @question.tags.pluck(:name).join(', ') %></p>

<p><%= image_tag @question.image.url(:large) if @question.image.present? %></p>

<p>
  <%= render '/likes/like' %>
</p>

<p>
  <% user_vote = @question.votes.find_by_user_id current_user %>

  <% if user_vote.nil? %>
    <%= link_to fa_icon('angle-up 3x'), question_votes_path(@question, is_up: true),
                           method: :post %>
    <br><span>( <%= @question.votes_count %> )</span>
    <br><%= link_to fa_icon('angle-down 3x'), question_votes_path(@question, is_up: false),
                             method: :post %>
  <% elsif user_vote.is_up? %>
    <%= link_to fa_icon('caret-up 3x'), question_vote_path(@question, user_vote),
                               method: :delete %>
    <br><span>( <%= @question.votes_count %> )</span>
    <br><%= link_to fa_icon('angle-down 3x'), question_vote_path(@question,
                                                user_vote,
                                                { is_up: false }),
                             method: :patch %>
  <% else %>
    <%= link_to fa_icon('angle-up 3x'), question_vote_path(@question,
                                              user_vote,
                                              { is_up: true }),
                             method: :patch %>
    <br><span>( <%= @question.votes_count %> )</span>
    <br><%= link_to fa_icon('caret-down 3x'), question_vote_path(@question, user_vote),
                               method: :delete %>
  <% end %>
</p>


<% if can? :edit, @question %>
  <%= link_to 'Edit', edit_question_path(@question) %>
<% end %>

  <%# Rails enables us to make links send non-GET requests by setting the method
  attribute for 'link_to'. Rails uses JavaScript to accomplish that. %>

<% if can? :destroy, @question %>
  <%= link_to 'Delete', question_path(@question),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
<% end %>


<h2>Answers</h2>
<%= render '/answers/form' %>

<hr>

<div id="answers">
  <% @question.answers.each do |ans| %>
    <%= render '/answers/answer', answer: ans %>
  <% end %>
</div>